#!/bin/sh --

jh_build --clean "$@"
jh_linkjars --unlink
jh_setupenvironment --clean
[ ! -f "debian/orbitdeps.debhelper" ] || rm "debian/orbitdeps.debhelper"
if [ -f "debian/.javahelper_clean" ]; then
	rm -f `cat debian/.javahelper_clean` debian/.javahelper_clean
fi

